[package]
name = "GiraffeParser"
version = "0.2.0"
edition = "2021"

[dependencies]
GiraffeLexer = { path = "../GiraffeLexer" }
GiraffeAST = { path = "../GiraffeAST" }
ordered-float = { version = "5.0.0" }