[package]
name = "GiraffeLexer"
version = "0.1.0"
edition = "2021"

[dependencies]
GiraffeAST = { path = "../GiraffeAST"}
regex="1.11.1"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
debug = false